/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The packet's final destination
 */
export type IlpAddress = string;
/**
 * ILP address prefix that this route advertisement covers.
 */
export type IlpAddress1 = string;
/**
 * A list of points describing the exchange rate curve (deprecated)
 */
export type Base64 = string;
/**
 * A list of Routes that have been added to the sending connector's table since the last update it has sent you.  May replace previously broadcast routes.
 */
export type Routes = {
  /**
   * the minimum difference (in seconds) between the source and destination transfers' expiries
   */
  min_message_window?: number;
  prefix: IlpAddress1;
  points?: Base64;
  /**
   * A list of ILP addresses of the connectors between the destination prefix and the advertising peer, exclusively. The list is ordered from closest to the destination first to furthest from the destination last.
   */
  path: string[];
  [k: string]: any;
}[];

/**
 * A routing update object
 */
export interface RoutingUpdate {
  /**
   * Time in milliseconds for which the sending connector claims its routes to be fresh, without another heartbeat
   */
  hold_down_time: number;
  /**
   * A list of accounts that have become unreachable through the sending connector
   */
  unreachable_through_me: IlpAddress[];
  /**
   * On this route broadcast, piggy-back a request for the other peer to send their full table in *their* next route broadcast
   */
  request_full_table?: boolean;
  new_routes: Routes;
}
